import { CardProps } from '@/types/types.ts'

export const dummyData: CardProps[] = [
  {
    type: 'فيلا',
    title: 'فيلا فخمة بالرياض',
    image: '/img.jpeg',
    tag: 'عقار مميز',
    location: 'الرياض',
    bathrooms: 4,
    rooms: 5,
    price: 2500000,
    condition: 'سكني',
  },
  {
    type: 'شقة',
    title: 'شقة بأجمل موقع في جدة',
    image: '/img.jpeg',
    tag: undefined,
    location: 'جدة',
    bathrooms: 2,
    rooms: 3,
    price: 800000,
    condition: 'جديد',
  },
  {
    type: 'ارض',
    title: 'ارض للبيع في الخبر',
    image: '/img.jpeg',
    tag: undefined,
    location: 'الخبر',
    bathrooms: 0,
    rooms: 0,
    price: 1200000,
    condition: 'جديد',
  },
  {
    type: 'قصر',
    title: 'قصر ملكي في الطائف',
    image: '/img.jpeg',
    tag: 'عقار مميز',
    location: 'الطائف',
    bathrooms: 8,
    rooms: 10,
    price: 15000000,
    condition: 'جديد',
  },
  {
    type: 'شالية',
    title: 'دور فاخر في الدمام',
    image: '/img.jpeg',
    tag: undefined,
    location: 'الدمام',
    bathrooms: 3,
    rooms: 4,
    price: 1500000,
    condition: 'سكني',
  },
  {
    type: 'شالية',
    title: 'شالية على البحر في جازان',
    image: '/img.jpeg',
    tag: undefined,
    location: 'جازان',
    bathrooms: 2,
    rooms: 3,
    price: 900000,
    condition: 'جديد',
  },
  {
    type: 'فيلا',
    title: 'فيلا مودرن في حائل',
    image: '/img.jpeg',
    tag: 'عقار مميز',
    location: 'حائل',
    bathrooms: 4,
    rooms: 6,
    price: 2800000,
    condition: 'جديد',
  },
  {
    type: 'شقة',
    title: 'شقة مفروشة في المدينة المنورة',
    image: '/img.jpeg',
    tag: undefined,
    location: 'المدينة المنورة',
    bathrooms: 2,
    rooms: 2,
    price: 600000,
    condition: 'جديد',
  },
  {
    type: 'ارض',
    title: 'ارض صناعية في عنيزة',
    image: '/img.jpeg',
    tag: undefined,
    location: 'عنيزة',
    bathrooms: 0,
    rooms: 0,
    price: 1500000,
    condition: 'جديد',
  },
  {
    type: 'قصر',
    title: 'قصر تاريخي في القصيم',
    image: '/img.jpeg',
    tag: 'عقار مميز',
    location: 'القصيم',
    bathrooms: 10,
    rooms: 12,
    price: 20000000,
    condition: 'جديد',
  },
  {
    type: 'فيلا',
    title: 'دور مستقل في تبوك',
    image: '/img.jpeg',
    tag: undefined,
    location: 'تبوك',
    bathrooms: 3,
    rooms: 4,
    price: 1300000,
    condition: 'جديد',
  },
  {
    type: 'شالية',
    title: 'شالية عصري في نجران',
    image: '/img.jpeg',
    tag: undefined,
    location: 'نجران',
    bathrooms: 2,
    rooms: 3,
    price: 850000,
    condition: 'جديد',
  },
  {
    type: 'فيلا',
    title: 'فيلا بحديقة في الباحة',
    image: '/img.jpeg',
    tag: 'عقار مميز',
    location: 'الباحة',
    bathrooms: 5,
    rooms: 7,
    price: 3200000,
    condition: 'جديد',
  },
  {
    type: 'شقة',
    title: 'شقة واسعة في بريدة',
    image: '/img.jpeg',
    tag: undefined,
    location: 'بريدة',
    bathrooms: 2,
    rooms: 3,
    price: 750000,
    condition: 'جديد',
  },
  {
    type: 'ارض',
    title: 'ارض زراعية في حفر الباطن',
    image: '/img.jpeg',
    tag: undefined,
    location: 'حفر الباطن',
    bathrooms: 0,
    rooms: 0,
    price: 1100000,
    condition: 'جديد',
  },
]
